# **Data Cleaning**

In [1]:
import pandas as pd
import numpy as np

# 1. LOAD DATASET

df = pd.read_csv("Day11_Messy_Company_Employee_Dataset.csv")

print("Dataset loaded successfully.")
print("Shape:", df.shape)

display(df.head())

Dataset loaded successfully.
Shape: (157, 12)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [4]:
# Data Inspection
print("\n--- Dataset Information ---")
df.info()

print("\n--- Statistical Summary ---")
display(df.describe(include="all"))

--- Dataset Information ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

--- Statistical Summary ---

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,157,157,152,157,153.000000,152,152.000000,154.000000,157,152,154.000000,155
unique,150,130,10,23,NaN,5,NaN,NaN,147,13,NaN,5
top,EMP0048,Nikhil Dar,Marketing,Data Scientist,NaN,Male,NaN,NaN,2025-08-17,Chandigarh,NaN,Remote
freq,2,3,23,13,NaN,75,NaN,NaN,2,24,NaN,56
mean,NaN,NaN,NaN,NaN,38.130719,NaN,89240.592105,8.990909,NaN,NaN,3.525974,NaN
std,NaN,NaN,NaN,NaN,9.361661,NaN,22626.172309,4.983874,NaN,NaN,0.930233,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,NaN,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,30.000000,NaN,71198.500000,4.450000,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,90046.500000,9.350000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,107328.000000,13.200000,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,NaN,NaN,5.000000,NaN

## Checking Missing Values

In [8]:
# Missing values in each column
print("Missing Values by Column:")
missing_values = df.isnull().sum()
display(missing_values)

print("\nTotal missing values:", df.isnull().sum().sum())

Missing Values by Column:

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

Total missing values: 32

In [12]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": missing_percentage.round(3)
})

missing_report

                   Missing_Count  Missing_Percentage
Employee_ID                    0               0.000
Employee_Name                  0               0.000
Department                     5               3.185
Job_Title                      0               0.000
Age                            4               2.548
Gender                         5               3.185
Annual_Salary                  5               3.185
Experience_Years               3               1.911
Joining_Date                   0               0.000
City                           5               3.185
Performance_Score              3               1.911
Work_Mode                      2               1.274

## Checking Duplicate Records

In [16]:
# Count duplicate rows
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

# Display duplicate records
display(df[df.duplicated(keep=False)])

Number of duplicate rows: 7

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
11,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
25,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
55,EMP0097,Zoya Shah,Finance,Financial Analyst,41.0,Male,81531.0,4.1,2023-06-05,Mumbai,4.0,Office
61,EMP0075,Manya Joshi,Sales,Sales Manager,29.0,Male,92623.0,11.9,2025-08-17,Jaipur,4.0,Hybrid
70,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
78,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
85,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
92,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote
100,EMP0139,Simran Sharma,Finance,Accountant,32.0,Female,110617.0,10.3,2021-08-03,Mumbai,3.0,Office
104,EMP0021,Riya Khan,Operations,Operations Executive,49.0,Female,71549.0,4.6,2024-09-20,Chandigarh,3.0,Hybrid
110,EMP0048,Nikhil Dar,Finance,Financial Analyst,27.0,Female,NaN,10.1,2020-06-18,Chandigarh,2.0,Office
112,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
139,EMP0150,Nikhil Khan,Finance,Finance Manager,43.0,Male,129905.0,16.3,2018-04-10,Chennai,3.0,Remote
156,EMP0120,Saira Sheikh,Marketing,Marketing Executive,52.0,Male,107328.0,17.4,2020-11-25,Bengaluru,2.0,Remote

In [18]:
df = df.drop_duplicates()
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

## Checking Inconsistent Categorical Value

In [21]:
categorical_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(df[column].value_counts(dropna=False))

--- Department ---
Department
Marketing           22
Engineering         21
Customer Success    20
Sales               18
Human Resources     16
Operations          16
Finance             15
Data & Analytics    15
NaN                  5
ENGINEERING          1
engineering          1
Name: count, dtype: int64

--- Gender ---
Gender
Male      71
Female    65
Other      7
NaN        5
female     1
MALE       1
Name: count, dtype: int64

--- City ---
City
Pune          23
Chandigarh    22
Jaipur        17
Hyderabad     14
Mumbai        13
Srinagar      13
Bengaluru     11
Delhi         11
Chennai        9
Kolkata        9
NaN            5
delhi          1
DELHI          1
Delhi          1
Name: count, dtype: int64

--- Work_Mode ---
Work_Mode
Remote    54
Hybrid    48
Office    44
NaN        2
REMOTE     1
remote     1
Name: count, dtype: int64

In [23]:
#Standardize inconsistent values
text_columns = [
    "Employee_Name",
    "Department",
    "Job_Title",
    "Gender",
    "City",
    "Work_Mode"
]

for column in text_columns:
    df[column] = df[column].astype("string").str.strip()

df["Department"] = df["Department"].str.title()
df["Gender"] = df["Gender"].str.title()
df["City"] = df["City"].str.title()
df["Work_Mode"] = df["Work_Mode"].str.title()

In [25]:
print(df.dtypes)

Employee_ID                  object
Employee_Name        string[python]
Department           string[python]
Job_Title            string[python]
Age                         float64
Gender               string[python]
Annual_Salary               float64
Experience_Years            float64
Joining_Date                 object
City                 string[python]
Performance_Score           float64
Work_Mode            string[python]
dtype: object

In [27]:
df["Joining_Date"] = pd.to_datetime(
    df["Joining_Date"],
    errors="coerce"
)
print(df.dtypes)

Employee_ID                  object
Employee_Name        string[python]
Department           string[python]
Job_Title            string[python]
Age                         float64
Gender               string[python]
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                 string[python]
Performance_Score           float64
Work_Mode            string[python]
dtype: object

## Handling Missing value in Numerical Column

In [30]:
numeric_columns = [
    "Age",
    "Annual_Salary",
    "Experience_Years",
    "Performance_Score"
]
print(df[numeric_columns].isnull().sum())

Age                  4
Annual_Salary        4
Experience_Years     3
Performance_Score    3
dtype: int64

In [32]:
for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

print(df[numeric_columns].isnull().sum())

Age                  0
Annual_Salary        0
Experience_Years     0
Performance_Score    0
dtype: int64

## Handling Missing Categorical value

In [35]:
categorical_columns = [
    "Department",
    "Gender",
    "City",
    "Work_Mode"
]

for column in categorical_columns:
    mode_value = df[column].mode()[0]
    df[column] = df[column].fillna(mode_value)

print(df[categorical_columns].isnull().sum())

Department    0
Gender        0
City          0
Work_Mode     0
dtype: int64

In [37]:
print("Missing Values After Cleaning")

display(df.isnull().sum())

print(
    "Total missing values:",
    df.isnull().sum().sum()
)

Missing Values After Cleaning

Employee_ID          0
Employee_Name        0
Department           0
Job_Title            0
Age                  0
Gender               0
Annual_Salary        0
Experience_Years     0
Joining_Date         0
City                 0
Performance_Score    0
Work_Mode            0
dtype: int64

Total missing values: 0

In [39]:
print("Duplicate rows after cleaning:", df.duplicated().sum())

Duplicate rows after cleaning: 0

In [41]:
print("Final Dataset Information:")
df.info()

print("Final Dataset:")
display(df.head(10))

Final Dataset Information:
<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 0 to 155
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        150 non-null    object
 1   Employee_Name      150 non-null    string
 2   Department         150 non-null    string
 3   Job_Title          150 non-null    string
 4   Age                150 non-null    float64
 5   Gender             150 non-null    string
 6   Annual_Salary      150 non-null    float64
 7   Experience_Years   150 non-null    float64
 8   Joining_Date       150 non-null    datetime64[ns]
 9   City               150 non-null    string
 10  Performance_Score  150 non-null    float64
 11  Work_Mode          150 non-null    string
dtypes: datetime64[ns](1), float64(4), object(1), string(6)
memory usage: 15.2+ KB
Final Dataset:

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.2,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.4,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.8,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.0,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.1,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.5,2020-06-28,Chennai,4.0,Remote

In [43]:
for column in categorical_columns:
    print(f"\n{column}:")
    print(df[column].unique())

Department:
<StringArray>
[     'Engineering',        'Marketing',  'Human Resources',
            'Sales',          'Finance', 'Data & Analytics',
 'Customer Success',       'Operations']
Length: 8, dtype: string

Gender:
<StringArray>
['Other', 'Female', 'Male']
Length: 3, dtype: string

City:
<StringArray>
[      'Pune',     'Mumbai',  'Bengaluru',     'Jaipur',  'Hyderabad',
    'Chennai', 'Chandigarh',   'Srinagar',    'Kolkata',      'Delhi']
Length: 10, dtype: string

Work_Mode:
<StringArray>
['Office', 'Remote', 'Hybrid']
Length: 3, dtype: string

In [45]:
df["Joining_Date"] = df["Joining_Date"].dt.strftime("%Y-%m-%d")

In [47]:
df.to_csv(
    "Cleaned_Company_Employee_Dataset_Day11.csv",
    index=False
)

print("Cleaned dataset exported successfully.")

Cleaned dataset exported successfully.

## Final Comparision

In [50]:
# Reload original dataset for comparison
original_df = pd.read_csv(
    "Day11_Messy_Company_Employee_Dataset.csv"
)

comparison = pd.DataFrame({
    "Measure": [
        "Number of Rows",
        "Number of Columns",
        "Total Missing Values",
        "Duplicate Rows"
    ],
    "Before Cleaning": [
        len(original_df),
        original_df.shape[1],
        original_df.isnull().sum().sum(),
        original_df.duplicated().sum()
    ],
    "After Cleaning": [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        df.duplicated().sum()
    ]
})

display(comparison)

                Measure  Before Cleaning  After Cleaning
0        Number of Rows              157             150
1     Number of Columns               12              12
2  Total Missing Values               32               0
3        Duplicate Rows                7               0

### Summary

The company employee dataset was first loaded and inspected using Pandas to identify missing values, duplicate records, inconsistent entries, and incorrect data types. Text fields were cleaned by removing extra spaces and standardizing capitalization of categorical values such as department, gender, city, and work mode. Numeric columns were converted to appropriate numeric data types, while the joining date was converted to a proper date format. Missing numerical values were filled using median imputation, and missing categorical values were filled using the mode. Duplicate records were identified using duplicated() and removed using drop_duplicates(). Finally, the cleaned dataset was verified to ensure that there were no remaining missing values or duplicate records, and it was exported as a CSV file.